In [1]:
import torch 

## 一、创建tensor

### 1.1 通过列表创建tensor

In [2]:
input_list = [[1., -1.], [1., 1.]]
torch.tensor(input_list)

tensor([[ 1., -1.],
        [ 1.,  1.]])

### 1.2 通过numpy创建tensor

In [3]:
import numpy as np

In [5]:
np_array = np.array(input_list)
torch.tensor(np_array)

tensor([[ 1., -1.],
        [ 1.,  1.]], dtype=torch.float64)

In [11]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 1.3 通过torch的API创建tensor

In [13]:
torch.empty([3, 4])  # 创建空数组

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.ones([3, 4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.rand([3, 4])  # 0到1之间的随机数

tensor([[0.2852, 0.6196, 0.6637, 0.6074],
        [0.4406, 0.0230, 0.2815, 0.7010],
        [0.0361, 0.7363, 0.6128, 0.2044]])

In [12]:
torch.randint(1, 10, ([3, 4]))  # 1到10之间的随机整数

tensor([[3, 7, 2, 9],
        [4, 1, 8, 6],
        [3, 9, 5, 6]])

In [14]:
torch.randn([3, 4])  # 标准正态分布

tensor([[-0.5553,  0.8696,  0.3765,  1.2163],
        [ 0.0449,  0.4354, -1.2732,  0.4431],
        [-0.8287,  0.3401,  1.8983, -0.0583]])

## 2、张量的属性与方法

In [15]:
a = torch.tensor(np.arange(1))

In [16]:
a

tensor([0])

### 2.1 获取tensor中的数据（tensor中只有一个元素可用）

In [17]:
a.item()

0

### 2.2 转化为numpy数组

In [18]:
a.numpy()  # 转换为numpy数组

array([0])

## 2.3 获取形状

In [43]:
input_list = [[1., 2., 5.], [3., 4., 6.]]
b = torch.tensor(input_list)

In [37]:
b.shape

torch.Size([2, 3])

In [38]:
b.size()

torch.Size([2, 3])

### 2.4 形状改变

In [39]:
b.view(3, 2)

tensor([[1, 2],
        [5, 3],
        [4, 6]])

## 2.5 获取维数

In [40]:
b.dim()

2

## 2.6 获取最大值

In [41]:
b.max()

tensor(6)

In [44]:
b.std() # 标准差

tensor(1.8708)

### 2.7 转置

In [45]:
b.t()

tensor([[1., 3.],
        [2., 4.],
        [5., 6.]])

In [46]:
c = torch.tensor(np.arange(24).reshape(2, 3, 4))

In [48]:
c.size()

torch.Size([2, 3, 4])

In [49]:
c.transpose(0, 1)  # 参数为要交换的维度

tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]])

In [50]:
c.permute(1, 2, 0)  # 参数表示维度，无论交换与否都要写出所有维度

tensor([[[ 0, 12],
         [ 1, 13],
         [ 2, 14],
         [ 3, 15]],

        [[ 4, 16],
         [ 5, 17],
         [ 6, 18],
         [ 7, 19]],

        [[ 8, 20],
         [ 9, 21],
         [10, 22],
         [11, 23]]])

## 2.8 取值

In [2]:
import torch
input_list = [[1., 2., 5.], [3., 4., 6.]]
c = torch.tensor(input_list)
c[1, 1]

tensor(4.)

In [3]:
c[1,1] = 5
c

tensor([[1., 2., 5.],
        [3., 5., 6.]])

## 二、tensor的数据类型

- torch.float32 or torch.float: 32-bit floating-point
- torch.float64 or torch.double: 64-bit, double-precision floating-point
- torch.float16 or torch.half: 16-bit, half-precision floating-point
- torch.int8: signed 8-bit integers
- torch.uint8: unsigned 8-bit integers
- torch.int16 or torch.short: signed 16-bit integers
- torch.int32 or torch.int: signed 32-bit integers
- torch.int64 or torch.long: signed 64-bit integers

In [4]:
c.dtype

torch.float32

In [6]:
torch.ones([3, 4], dtype=torch.int8)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)

In [11]:
import numpy as np
torch.tensor(np.arange(12,dtype=np.int32))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)

In [12]:
c

tensor([[1., 2., 5.],
        [3., 5., 6.]])

In [14]:
c.type(torch.int8)

tensor([[1, 2, 5],
        [3, 5, 6]], dtype=torch.int8)

In [15]:
c.double()

tensor([[1., 2., 5.],
        [3., 5., 6.]], dtype=torch.float64)

## 3、tensor的其他操作

### 相加

In [20]:
x = torch.ones([5, 3])
x = x.new_ones(5, 3, dtype=torch.float)
y = torch.rand(5, 3)
x + y

tensor([[1.5371, 1.4904, 1.9680],
        [1.6419, 1.2310, 1.2089],
        [1.9703, 1.3485, 1.1429],
        [1.5226, 1.2849, 1.7036],
        [1.7538, 1.3329, 1.1307]])

In [17]:
torch.add(x, y) 

tensor([[1.7674, 1.6299, 1.3539],
        [1.0703, 1.3685, 1.9434],
        [1.6651, 1.0482, 1.8796],
        [1.9837, 1.6295, 1.4039],
        [1.0200, 1.3541, 1.1140]])

In [21]:
x.add(y)

tensor([[1.5371, 1.4904, 1.9680],
        [1.6419, 1.2310, 1.2089],
        [1.9703, 1.3485, 1.1429],
        [1.5226, 1.2849, 1.7036],
        [1.7538, 1.3329, 1.1307]])

In [22]:
x.add_(y)  # 原地操作

tensor([[1.5371, 1.4904, 1.9680],
        [1.6419, 1.2310, 1.2089],
        [1.9703, 1.3485, 1.1429],
        [1.5226, 1.2849, 1.7036],
        [1.7538, 1.3329, 1.1307]])

In [23]:
x

tensor([[1.5371, 1.4904, 1.9680],
        [1.6419, 1.2310, 1.2089],
        [1.9703, 1.3485, 1.1429],
        [1.5226, 1.2849, 1.7036],
        [1.7538, 1.3329, 1.1307]])

In [24]:
x + 10

tensor([[11.5371, 11.4904, 11.9680],
        [11.6419, 11.2310, 11.2089],
        [11.9703, 11.3485, 11.1429],
        [11.5226, 11.2849, 11.7036],
        [11.7538, 11.3329, 11.1307]])

### CUDA中的tensor

In [26]:
# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device = torch.device("cuda:0" if torch.cuda.is_available() else "mps")

In [27]:
device

device(type='mps')

In [32]:
# if torch.cuda.is_available():
# device = torch.device("cuda")          # a CUDA device object
device = torch.device("mps")
y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
x = x.to(device)  # 或者使用`.to("cuda")`将tensor移动到cuda上
z = x + y
print(z)
print(z.to("cpu", torch.float32))  # `.to`也能在移动时改变dtype

tensor([[2.5371, 2.4904, 2.9680],
        [2.6419, 2.2310, 2.2089],
        [2.9703, 2.3485, 2.1429],
        [2.5226, 2.2849, 2.7036],
        [2.7538, 2.3329, 2.1307]], device='mps:0')
tensor([[2.5371, 2.4904, 2.9680],
        [2.6419, 2.2310, 2.2089],
        [2.9703, 2.3485, 2.1429],
        [2.5226, 2.2849, 2.7036],
        [2.7538, 2.3329, 2.1307]])
