# tensor的创建方法

In [4]:
import torch
import numpy as np
torch.manual_seed(1)
# 判断是否有GPU资源


## 创建tensor

In [10]:
# ===============================  exmaple 1 ===============================
# 通过torch.tensor创建张量
# 创建全1张量
arr = np.ones((3, 3))
print("ndarray的数据类型：", arr.dtype)
# 创建存放在 GPU 的数据
# t = torch.tensor(arr, device='cuda')
# t = torch.tensor(data=arr, dtype=torch.float32, device="mps")
t = torch.tensor(arr)
print(t)

ndarray的数据类型： float64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
# ===============================  exmaple 2 ===============================
# 通过torch.from_numpy创建张量
# 通过已有的numpy数组创建tensor
arr = np.array([[1, 2, 3], [4, 5, 6]])
t = torch.from_numpy(arr)

# 修改 array，tensor 也会被修改
print("\n修改arr")
arr[0, 0] = 0
print("numpy array: ", arr)
print("tensor : ", t)

# 修改 tensor，array 也会被修改
print("\n修改tensor")
t[0, 0] = -1
print("numpy array: ", arr)
print("tensor : ", t)


修改arr
numpy array:  [[0 2 3]
 [4 5 6]]
tensor :  tensor([[0, 2, 3],
        [4, 5, 6]])

修改tensor
numpy array:  [[-1  2  3]
 [ 4  5  6]]
tensor :  tensor([[-1,  2,  3],
        [ 4,  5,  6]])


In [12]:
# ===============================  exmaple 3 ===============================
# 通过torch.zeros创建张量

out_t = torch.tensor([1])
# 这里制定了 out
t = torch.zeros((3, 3), out=out_t)
print(t, '\n', out_t)
# id 是取内存地址。最终 t 和 out_t 是同一个内存地址
print(id(t), id(out_t), id(t) == id(out_t))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
4696071200 4696071200 True


- torch.zeros_like()
- torch.ones()
- torch.ones_like()

In [13]:
# ===============================  exmaple 4 ===============================
# 通过torch.full创建全1张量

t = torch.full((3, 3), 1)
print(t)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


- torch.full_like()

In [14]:
# ===============================  exmaple 5 ===============================
# 通过torch.arange创建等差数列张量
t = torch.arange(2, 10, 2)
print(t)

tensor([2, 4, 6, 8])


In [15]:
# ===============================  exmaple 6 ===============================
# 通过torch.linspace创建均分数列张量
t = torch.linspace(2, 10, 5)
print(t)

tensor([ 2.,  4.,  6.,  8., 10.])


- torch.logspace()
- torch.eye()

In [16]:
# ===============================  exmaple 7 ===============================
# 通过torch.normal创建正态分布张量

# mean：张量 std: 张量
mean = torch.arange(1, 5, dtype=torch.float)
std = torch.arange(1, 5, dtype=torch.float)
t_normal = torch.normal(mean, std)
print("mean:{}\nstd:{}".format(mean, std))
print(t_normal)

# mean：标量 std: 标量
# 这里需要设置 size
t_normal = torch.normal(0., 1., size=(4,))
print(t_normal)

# mean：张量 std: 标量
mean = torch.arange(1, 5, dtype=torch.float)
std = 1
t_normal = torch.normal(mean, std)
print("mean:{}\nstd:{}".format(mean, std))
print(t_normal)

mean:tensor([1., 2., 3., 4.])
std:tensor([1., 2., 3., 4.])
tensor([1.6614, 2.5338, 3.1850, 6.4853])
tensor([-0.4519, -0.1661, -1.5228,  0.3817])
mean:tensor([1., 2., 3., 4.])
std:1
tensor([-0.0276,  1.4369,  2.1077,  3.9417])


- torch.randn()
- torch.randn_like()
- torch.rand()
- torch.rand_like()
- torch.randint()
- torch.randint_like()
- torch.randperm()
- torch.bernoulli()

## 拼接

In [17]:
# 按维度进行拼接
t = torch.ones((2, 3))
t_0 = torch.cat([t, t], dim=0)
t_1 = torch.cat([t, t], dim=1)
print("t_0:{} shape:{}\nt_1:{} shape:{}".format(t_0, t_0.shape, t_1, t_1.shape))

t_0:tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) shape:torch.Size([4, 3])
t_1:tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]) shape:torch.Size([2, 6])


In [20]:
# 在新创建的维度上进行拼接
t = torch.ones((2, 3))
# dim = 2
t_stack = torch.stack([t, t, t], dim=2)  # 按列拼接
print("\nt_stack.shape:{}".format(t_stack.shape))
print(t_stack)
# dim = 1
t_stack = torch.stack([t, t, t], dim=1)  # 按行拼接
print("\nt_stack.shape:{}".format(t_stack.shape))
print(t_stack)
# dim = 0
t_stack = torch.stack([t, t, t], dim=0)  # 按深度拼接
print("\nt_stack.shape:{}".format(t_stack.shape))
print(t_stack)


t_stack.shape:torch.Size([2, 3, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

t_stack.shape:torch.Size([2, 3, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

t_stack.shape:torch.Size([3, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [27]:
t1 = torch.tensor([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
t2 = torch.tensor([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

t_stack = torch.stack([t1, t2], dim=0)
print(t_stack.shape)
t_stack

torch.Size([2, 3, 3])


tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]])

In [23]:
t1 = torch.tensor([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
t2 = torch.tensor([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

t_stack = torch.stack([t1, t2], dim=1)
print(t_stack.shape)
t_stack

torch.Size([3, 2, 3])


tensor([[[ 1,  2,  3],
         [10, 20, 30]],

        [[ 4,  5,  6],
         [40, 50, 60]],

        [[ 7,  8,  9],
         [70, 80, 90]]])

In [25]:
t1 = torch.tensor([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
t2 = torch.tensor([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

t_stack = torch.stack([t1, t2], dim=2)
print(t_stack.shape)
t_stack

torch.Size([3, 3, 2])


tensor([[[ 1, 10],
         [ 2, 20],
         [ 3, 30]],

        [[ 4, 40],
         [ 5, 50],
         [ 6, 60]],

        [[ 7, 70],
         [ 8, 80],
         [ 9, 90]]])

## 切分

In [28]:
a = torch.ones((2, 7))  # 7
list_of_tensors = torch.chunk(a, dim=1, chunks=3)   # 3
for idx, t in enumerate(list_of_tensors):
    print("第{}个张量：{}, shape is {}".format(idx+1, t, t.shape))

第1个张量：tensor([[1., 1., 1.],
        [1., 1., 1.]]), shape is torch.Size([2, 3])
第2个张量：tensor([[1., 1., 1.],
        [1., 1., 1.]]), shape is torch.Size([2, 3])
第3个张量：tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])


In [29]:
t = torch.ones((2, 5))
list_of_tensors = torch.split(t, [2, 1, 2], dim=1)
for idx, t in enumerate(list_of_tensors):
    print("第{}个张量：{}, shape is {}".format(idx+1, t, t.shape))

第1个张量：tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])
第2个张量：tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])
第3个张量：tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])


## 索引

In [30]:
# 创建均匀分布
t = torch.randint(0, 9, size=(3, 3))
# 注意 idx 的 dtype 不能指定为 torch.float
idx = torch.tensor([0, 2], dtype=torch.long)
# 取出第 0 行和第 2 行
t_select = torch.index_select(t, dim=0, index=idx)
print("t:\n{}\nt_select:\n{}".format(t, t_select))

t:
tensor([[6, 0, 7],
        [8, 8, 4],
        [5, 2, 6]])
t_select:
tensor([[6, 0, 7],
        [5, 2, 6]])


In [31]:
t = torch.randint(0, 9, size=(3, 3))
mask = t.le(5)  # ge is mean greater than or equal/   gt: greater than  le  lt
# 取出大于 5 的数
t_select = torch.masked_select(t, mask)
print("t:\n{}\nmask:\n{}\nt_select:\n{} ".format(t, mask, t_select))

t:
tensor([[6, 7, 6],
        [8, 6, 2],
        [2, 6, 5]])
mask:
tensor([[False, False, False],
        [False, False,  True],
        [ True, False,  True]])
t_select:
tensor([2, 2, 5]) 


## 变换

In [32]:
# 生成 0 到 8 的随机排列
t = torch.randperm(8)
# -1 表示这个维度是根据其他维度计算得出的
t_reshape = torch.reshape(t, (-1, 2, 2))
print("t:{}\nt_reshape:\n{}".format(t, t_reshape))

t:tensor([1, 5, 0, 3, 6, 2, 7, 4])
t_reshape:
tensor([[[1, 5],
         [0, 3]],

        [[6, 2],
         [7, 4]]])


In [33]:
# 修改张量 t 的第 0 个元素，张量 t_reshape 也会被改变
t[0] = 1024
print("t:{}\nt_reshape:\n{}".format(t, t_reshape))
print("t.data 内存地址:{}".format(id(t.data)))
print("t_reshape.data 内存地址:{}".format(id(t_reshape.data)))

t:tensor([1024,    5,    0,    3,    6,    2,    7,    4])
t_reshape:
tensor([[[1024,    5],
         [   0,    3]],

        [[   6,    2],
         [   7,    4]]])
t.data 内存地址:4695902064
t_reshape.data 内存地址:4695902064


In [35]:
#把 c * h * w 变换为 c * w * h
t = torch.rand((2, 3, 4))
t_transpose = torch.transpose(t, dim0=1, dim1=2)    # c*h*w     c*w*h
print("t shape:{}\nt_transpose shape: {}".format(t.shape, t_transpose.shape))
print(t)
print(t_transpose)

t shape:torch.Size([2, 3, 4])
t_transpose shape: torch.Size([2, 4, 3])
tensor([[[0.5285, 0.6642, 0.6099, 0.6818],
         [0.7479, 0.0369, 0.7517, 0.1484],
         [0.1227, 0.5304, 0.4148, 0.7937]],

        [[0.2104, 0.0555, 0.8639, 0.4259],
         [0.7812, 0.6607, 0.1251, 0.6004],
         [0.6201, 0.1652, 0.2628, 0.6705]]])
tensor([[[0.5285, 0.7479, 0.1227],
         [0.6642, 0.0369, 0.5304],
         [0.6099, 0.7517, 0.4148],
         [0.6818, 0.1484, 0.7937]],

        [[0.2104, 0.7812, 0.6201],
         [0.0555, 0.6607, 0.1652],
         [0.8639, 0.1251, 0.2628],
         [0.4259, 0.6004, 0.6705]]])


- torch.t()  二维张量转置

In [36]:
# 维度 0 和 3 的长度是 1
t = torch.rand((1, 2, 3, 1))
# 可以移除维度 0 和 3
t_sq = torch.squeeze(t)
# 可以移除维度 0
t_0 = torch.squeeze(t, dim=0)
# 不能移除 1
t_1 = torch.squeeze(t, dim=1)
print("t.shape: {}".format(t.shape))
print("t_sq.shape: {}".format(t_sq.shape))
print("t_0.shape: {}".format(t_0.shape))
print("t_1.shape: {}".format(t_1.shape))

t.shape: torch.Size([1, 2, 3, 1])
t_sq.shape: torch.Size([2, 3])
t_0.shape: torch.Size([2, 3, 1])
t_1.shape: torch.Size([1, 2, 3, 1])


- torch.unsqueeze()  维度扩展